### PR TITLE
Very minor typo "currrent" -> "current"

### PR DESCRIPTION
**Pull request by dneiss**

### CODE REVIEW

**Comment by tupton** [comment]
Thanks!

**Comment by dneiss** [comment]
Hi Thomas, Funny to get a response to quickly.

Im just sitting in a cafe here in Mountain View trying to brush up on my
Python and pulled your code just to give me something to look at and work
on. Am seeing some other issues that I might push up just to help out. Im
not Python expert, just a wanna be expert looking to practice.

**Comment by tupton** [comment]
Awesome! This code is very old. I'm looking at it now and wondering what on earth I was thinking when I wrote it. That thinking happens with code that I wrote five months ago, let alone five years ago.

By all means, create a pull request for any fixes or enhancements you write. Let me know if I can help!

**Comment by dneiss** [comment]
Ok, submitted changes for pylinting of file. No biggies.

Im trying to get into the Python idioms and just write more Pythonic code.

**Pull request merged**
